server:
  port: 8083
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    drive-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

springdoc:
  api-doc:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: WARN

encryption:
  key: ${ENCRYPTION_KEY}
  iv: ${ENCRYPTION_IV}
